### ISSUE TITLE
Eliminate or document bash dependency

### ISSUE THREAD

**Issue by kagminjeong** [grahamc/git-cachecow#1]
https://github.com/grahamc/git-cachecow/blob/master/git-scclone requires bash and therefore won't work on systems that do not have bash.

Ideally the script should be rewritten to use posix sh only, if that is not possible bash dependency should be documented.

**Comment by grahamc** [comment]
For consistency, I'm going to rewrite git-scclone in Python.

**Comment by grahamc** [comment]
Eliminated.

Bonus: install with `pip install git-cachecow`.
